/// Generated by AssetsRefGenerator on 2021/07/23
class Res {
  static const String beef = "assets/additives/beef.png";
  static const String chicken = "assets/additives/chicken.png";
  static const String Ei = "assets/additives/Ei.png";
  static const String En = "assets/additives/En.png";
  static const String Fi = "assets/additives/Fi.png";
  static const String Gl = "assets/additives/Gl.png";
  static const String Kn = "assets/additives/Kn.png";
  static const String Kr = "assets/additives/Kr.png";
  static const String Lu = "assets/additives/Lu.png";
  static const String Mi = "assets/additives/Mi.png";
  static const String pig = "assets/additives/pig.png";
  static const String Sc = "assets/additives/Sc.png";
  static const String Se = "assets/additives/Se.png";
  static const String Sf = "assets/additives/Sf.png";
  static const String Sl = "assets/additives/Sl.png";
  static const String So = "assets/additives/So.png";
  static const String Sw = "assets/additives/Sw.png";
  static const String vegan = "assets/additives/vegan.png";
  static const String vegetarian = "assets/additives/vegetarian.png";
  static const String Wt = "assets/additives/Wt.png";
  static const String lageplan = "assets/lageplan.png";
  static const String license = "assets/license.txt";
  static const String logo = "assets/logo.png";
  static const String sleep = "assets/sleep.png";
  static const String arrow_drop_down = "images/arrow_drop_down.png";
  static const String calendar = "images/calendar.png";
  static const String check = "images/check.png";
  static const String cross = "images/cross.png";
  static const String edit = "images/edit.png";
  static const String plus = "images/plus.png";
  static const String refresh = "images/refresh.png";
  static const String scan = "images/scan.png";
  static const String search = "images/search.png";
  static const String share = "images/share.png";
  static const String trash = "images/trash.png";
  static const String x = "images/x.png";
  static const String cultures = "data/cultures/cultures.bin";
  static const String tzdb = "data/tzdb/tzdb.bin";
}

class Packages {
  static const String time_machine = "time_machine";
}
